// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Bridge from "./Bridge.bs.js";

var ht = Bridge.hello(undefined);

window.top.postMessage({
  a: ht,
});

export { ht };
/* ht Not a pure module */
